project_name: kubemart
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
    ldflags:
      - -s -w -X github.com/kubemart/kubemart/cmd.VersionCli={{.Version}} -X github.com/kubemart/kubemart/cmd.CommitCli={{.Commit}} -X github.com/kubemart/kubemart/cmd.DateCli={{.Date}}
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.sha256"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: kubemart
    tap:
      owner: civo
      name: homebrew-tools
    commit_author:
      name: civobot
      email: hello@civo.com
    folder: Formula
    homepage: "https://github.com/kubemart/kubemart-cli"
    description: "CLI for interacting with your Kubemart apps"
nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Arch }}"
    homepage: https://github.com/kubemart/kubemart-cli
    maintainer: Civo <hello@civo.com>
    description: A Command Line Interface (CLI) for interacting with your Kubemart apps
    license: MIT
    vendor: Civo
    formats:
      - deb
      - rpm
