name: main
on: push

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup tests environment
        run: |
          chmod +x ./pkg/utils/setup_test.sh
          ./pkg/utils/setup_test.sh

      - name: Run tests
        run: |
          chmod +x ./pkg/utils/run_test.sh
          ./pkg/utils/run_test.sh

      - name: Post tests clean-up
        run: |
          chmod +x ./pkg/utils/post_test.sh
          ./pkg/utils/post_test.sh

  # =======================================================================

  new-release:
    # only run this job if the push contains a tag like v1.2.3
    if: startsWith(github.ref, 'refs/tags/v')
    # run-tests job must complete successfully before this job will run
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x

      - name: Build and release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
