name: new-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  new-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x

      - name: Set up Go Modules
        env:
          GOPRIVATE: github.com/kubemart/kubemart-operator
        run: |
          git config --global url."https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com".insteadOf "https://github.com"

      # TODO - change this after we go live
      - name: Download kubemart-operator manifest
        uses: dsaltares/fetch-gh-release-asset@939be9e72e81fe7009b6112bc96abde38bf7b68f
        with:
          repo: "kubemart/kubemart-operator"
          version: "latest"
          file: "kubemart-operator.yaml"
          target: "cmd/manifests/kubemart-operator.yaml"
          token: ${{ secrets.GH_TOKEN }}

      - name: Build and release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
